### ISSUE TITLE
BurgerMenu.svelte:5:19 Unexpected token

### ISSUE THREAD

**Issue by norricorp** [jorisBarkema/svelte-burger-menu#10]
Hi,
I noticed that the demo in svelte repl fails with the above error.
I tried creating a test svelte project using vite and get same result; build fails

Error: Build failed with 1 error:
node_modules/svelte-burger-menu/src/BurgerMenu.svelte:5:19: ERROR: [plugin: vite-plugin-svelte:optimize-svelte] C:\temp\burgermenu\node_modules\svelte-burger-menu\src\BurgerMenu.svelte:5:19 Unexpected token
    at failureErrorWithLog (C:\temp\burgermenu\node_modules\esbuild\lib\main.js:1604:15)
    at C:\temp\burgermenu\node_modules\esbuild\lib\main.js:1056:28
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  errors: [
    {
      detail: undefined,
      id: '',
      location: {
        column: 19,
        file: 'node_modules/svelte-burger-menu/src/BurgerMenu.svelte',
        length: 0,
        line: 5,
        lineText: '   export let open: boolean = false;\r',
        namespace: 'file',
        suggestion: ''
      },
      notes: [
        {
          location: {
            column: 35,
            file: 'node_modules/svelte-burger-menu/src/index.ts',
            length: 21,
            line: 1,
            lineText: "export { default as default } from './BurgerMenu.svelte';",
            namespace: '',
            suggestion: ''
          },
          text: 'The plugin "vite-plugin-svelte:optimize-svelte" was triggered by this import'
        }
      ],
      pluginName: 'vite-plugin-svelte:optimize-svelte',
      text: 'C:\\temp\\burgermenu\\node_modules\\svelte-burger-menu\\src\\BurgerMenu.svelte:5:19 Unexpected token'
    }
  ],
  warnings: []
}
Any ideas what has gone wrong?

**Comment by jorisBarkema** [comment]
Honestly don't know, my best bet is that it's typescript related but I have not touched this in a long time and have no plans on putting more effort into this sorry. You could try version 1.0.5 if typescript is not required for your project and if you do find the issue I am happy to merge a fix.

**Comment by norricorp** [comment]
Thanks for getting back so quickly.
The important thing is knowing that the project is not being actively developed any more, which is prefectly understandable.
